#!/bin/bash

builddir/./server &
server_pid=$!


builddir/./client &
client_pid=$!
echo "-------------------------------------------------------------------------------------------------------------------------------------------------------------------"
sleep 0.5
kill $client_pid
kill $server_pid